[package]
name = "mapgen"
version = "0.1.0"
authors = ["wareya <wareya@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1.3.4"

[dependencies.pancurses]
version = "0.16"
features = ["win32"]
